### ISSUE TITLE
no python application found

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#110]
**Describe the bug**
Internal Server Error:
Cannot start the service in local using docker compose:
```sh
$ docker-compose up
....
flask_1            | --- no python application found, check your startup logs for errors ---
```

**To Reproduce**
Follow steps at README (To deploy the application)

**Expected behavior**
Go to https://localhost and see the page.

**Full stack**
```sh
$ docker-compose up
WARNING: Service "flask" uses secret "oidc_secret" with uid, gid, or mode. These fields are not supported by this implementation of the Compose file
WARNING: Service "flask" uses secret "cookie_secret" with uid, gid, or mode. These fields are not supported by this implementation of the Compose file
Creating network "eosc-perf_default" with the default driver
Creating eosc-perf_sqlite-backuper_1 ... done
Creating eosc-perf_flask_1           ... done
Creating eosc-perf_certbot_1         ... done
Creating eosc-perf_nginx_1           ... done
Attaching to eosc-perf_certbot_1, eosc-perf_flask_1, eosc-perf_sqlite-backuper_1, eosc-perf_nginx_1
certbot_1          | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1          | 
certbot_1          | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1          | No renewals were attempted.
certbot_1          | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
flask_1            | [uWSGI] getting INI configuration from uwsgi.ini
flask_1            | *** Starting uWSGI 2.0.19.1 (64bit) on [Fri Mar 26 10:36:13 2021] ***
flask_1            | compiled with version: 8.3.0 on 26 March 2021 10:17:05
flask_1            | os: Linux-5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021
flask_1            | nodename: 7162d325c67e
flask_1            | machine: x86_64
flask_1            | clock source: unix
flask_1            | pcre jit disabled
flask_1            | detected number of CPU cores: 16
flask_1            | current working directory: /app
flask_1            | detected binary path: /usr/local/bin/uwsgi
flask_1            | your memory page size is 4096 bytes
flask_1            | detected max file descriptor number: 1048576
flask_1            | lock engine: pthread robust mutexes
flask_1            | thunder lock: disabled (you can enable it with --thunder-lock)
flask_1            | uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 3
flask_1            | Python version: 3.8.4 (default, Jul 14 2020, 02:56:59)  [GCC 8.3.0]
flask_1            | *** Python threads support is disabled. You can enable it with --enable-threads ***
flask_1            | Python main interpreter initialized at 0x5646f66d2000
flask_1            | your server socket listen backlog is limited to 100 connections
flask_1            | your mercy for graceful operations on workers is 60 seconds
flask_1            | mapped 437520 bytes (427 KB) for 5 cores
flask_1            | *** Operational MODE: preforking ***
nginx_1            | /nginx-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1            | /nginx-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
flask_1            | Running in production mode
nginx_1            | /nginx-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
flask_1            | Traceback (most recent call last):
flask_1            |   File "./eosc_perf/wsgi_instance.py", line 3, in <module>
nginx_1            | 2021/03/26 10:36:14 [notice] 15#15: signal process started
nginx_1            | 2021/03/26 10:36:14 [error] 15#15: open() "/var/run/nginx.pid" failed (2: No such file or directory)
nginx_1            | nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)
flask_1            |     flask_app = create_app()
flask_1            |   File "./eosc_perf/flask_factory.py", line 46, in create_app
nginx_1            | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
sqlite-backuper_1  | crond: crond (busybox 1.32.1) started, log level 8
flask_1            |     configure_database(flask_application)
flask_1            |   File "./eosc_perf/model/database.py", line 34, in configure_database
flask_1            |     db.create_all()
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
flask_1            |     self._execute_for_all_tables(app, bind, 'create_all')
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
nginx_1            | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx_1            | /nginx-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
flask_1            |     op(bind=self.get_engine(app, bind), **extra)
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
flask_1            |     return connector.get_engine()
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
flask_1            |     options = self.get_options(sa_url, echo)
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
flask_1            |     self._sa.apply_driver_hacks(self._app, sa_url, options)
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
flask_1            |     sa_url.database = os.path.join(app.root_path, sa_url.database)
flask_1            | AttributeError: can't set attribute
flask_1            | unable to load app 0 (mountpoint='') (callable not found or import error)
flask_1            | *** no app loaded. going in full dynamic mode ***
flask_1            | *** uWSGI is running in multiple interpreter mode ***
flask_1            | spawned uWSGI master process (pid: 1)
nginx_1            | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/app.conf.template to /etc/nginx/conf.d/app.conf
nginx_1            | /nginx-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
flask_1            | spawned uWSGI worker 1 (pid: 8, cores: 1)
flask_1            | spawned uWSGI worker 2 (pid: 9, cores: 1)
flask_1            | spawned uWSGI worker 3 (pid: 10, cores: 1)
flask_1            | spawned uWSGI worker 4 (pid: 11, cores: 1)
flask_1            | spawned uWSGI worker 5 (pid: 12, cores: 1)
nginx_1            | /nginx-entrypoint.sh: Configuration complete; ready for start up
nginx_1            | GET /nginx/reload HTTP/1.0
nginx_1            | Host: localhost:9000
nginx_1            | Connection: close
nginx_1            | Authorization: Basic bmdpbng6c2RmYXNkZmRhc2Zkc2F4Y3Zhc2Rm
nginx_1            | User-Agent: curl/7.69.1
nginx_1            | Accept: */*
nginx_1            | 
nginx_1            | 172.19.0.3 - nginx [26/Mar/2021:10:36:14 +0000] "GET /nginx/reload HTTP/1.1" 200 67 "-" "curl/7.69.1" "-"
certbot_1          | NGINX reload requested at: Fri Mar 26 10:36:14 UTC 2021
nginx_1            | 2021/03/26 10:36:15 [notice] 63#63: signal process started
flask_1            | --- no python application found, check your startup logs for errors ---
flask_1            | [pid: 10|app: -1|req: -1/1] 172.19.0.1 () {56 vars in 2076 bytes} [Fri Mar 26 10:36:21 2021] GET / => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
nginx_1            | 172.19.0.1 - - [26/Mar/2021:10:36:21 +0000] "GET / HTTP/2.0" 500 21 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
flask_1            | --- no python application found, check your startup logs for errors ---
flask_1            | [pid: 10|app: -1|req: -1/2] 172.19.0.1 () {56 vars in 2026 bytes} [Fri Mar 26 10:36:21 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
nginx_1            | 172.19.0.1 - - [26/Mar/2021:10:36:21 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "https://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
```

**Comment by TheChristophe** [comment]
The actual error here is 

```
flask_1            | Traceback (most recent call last):
flask_1            |   File "./eosc_perf/wsgi_instance.py", line 3, in <module>
flask_1            |     flask_app = create_app()
flask_1            |   File "./eosc_perf/flask_factory.py", line 46, in create_app
flask_1            |     configure_database(flask_application)
flask_1            |   File "./eosc_perf/model/database.py", line 34, in configure_database
flask_1            |     db.create_all()
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
flask_1            |     self._execute_for_all_tables(app, bind, 'create_all')
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
flask_1            |     op(bind=self.get_engine(app, bind), **extra)
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
flask_1            |     return connector.get_engine()
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
flask_1            |     options = self.get_options(sa_url, echo)
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
flask_1            |     self._sa.apply_driver_hacks(self._app, sa_url, options)
flask_1            |   File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
flask_1            |     sa_url.database = os.path.join(app.root_path, sa_url.database)
```

What is your database path/EOSC_PERF_DB_PATH set to?

**Comment by TheChristophe** [comment]
I've been able to reproduce this, the solution is to upgrade flask-sqlachemy.
